/*
 * wolscheduler - Wake-on-LAN scheduler and keep-alive daemon for pfSense.
 *
 * Features:
 *   - Sends a WOL magic packet to each host every N seconds (schedule).
 *   - Keep-alive: pings each host; when it stops answering, sends WOL every
 *     `wol_retry` seconds until it answers again.
 *
 * Config file (generated by the pfSense GUI), INI-like:
 *
 *   [host]
 *   name = Workstation
 *   mac = 00:11:22:33:44:55
 *   broadcast = 192.168.1.255
 *   port = 9
 *   interval = 3600          # seconds between scheduled WOL (0 = off)
 *   keepalive = 1
 *   ip = 192.168.1.10
 *   ping_interval = 10       # seconds between pings
 *   ping_timeout = 2         # seconds to wait for a reply
 *   fail_threshold = 3       # consecutive lost pings to consider host down
 *   wol_retry = 30           # seconds between WOL while host is down
 *
 * Signals: SIGHUP reloads the config, SIGTERM/SIGINT exit.
 */

#include <sys/types.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>

#include <netinet/in.h>
#include <netinet/in_systm.h>
#include <netinet/ip.h>
#include <netinet/ip_icmp.h>
#include <arpa/inet.h>

#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <syslog.h>
#include <time.h>
#include <unistd.h>

#define VERSION            "1.0.0"
#define DEFAULT_CONF       "/usr/local/etc/wolscheduler.conf"
#define DEFAULT_PIDFILE    "/var/run/wolscheduler.pid"
#define DEFAULT_STATUSFILE "/var/run/wolscheduler.status"
#define MAX_HOSTS          256
#define NAME_LEN           64

enum host_state { ST_UNKNOWN = 0, ST_UP, ST_DOWN };

struct host {
	char            name[NAME_LEN];
	uint8_t         mac[6];
	struct in_addr  bcast;
	uint16_t        port;
	int             interval;
	int             keepalive;
	struct in_addr  ip;
	int             ping_interval;
	int             ping_timeout;
	int             fail_threshold;
	int             wol_retry;

	/* runtime state */
	enum host_state state;
	time_t          next_wol;       /* scheduled WOL */
	time_t          next_ping;
	time_t          next_retry_wol; /* keep-alive WOL while down */
	int             ping_pending;
	time_t          ping_sent;
	uint16_t        ping_seq;
	int             fails;
	time_t          last_reply;
	time_t          last_wol;
	unsigned long   wol_count;
};

static struct host hosts[MAX_HOSTS];
static int         nhosts;

static const char *conf_path = DEFAULT_CONF;
static const char *pid_path = DEFAULT_PIDFILE;
static const char *status_path = DEFAULT_STATUSFILE;
static int         foreground;
static int         debug;

static volatile sig_atomic_t got_hup;
static volatile sig_atomic_t got_term;

static int      icmp_sock = -1;
static uint16_t ping_ident;
static uint16_t ping_counter;

static void
logmsg(int prio, const char *fmt, ...)
{
	va_list ap;

	if (prio == LOG_DEBUG && !debug)
		return;
	va_start(ap, fmt);
	if (foreground) {
		vfprintf(stderr, fmt, ap);
		fputc('\n', stderr);
	} else {
		vsyslog(prio, fmt, ap);
	}
	va_end(ap);
}

/* ---------- helpers ---------- */

static char *
trim(char *s)
{
	char *e;

	while (isspace((unsigned char)*s))
		s++;
	e = s + strlen(s);
	while (e > s && isspace((unsigned char)e[-1]))
		*--e = '\0';
	return s;
}

static int
parse_mac(const char *s, uint8_t mac[6])
{
	unsigned int b[6];
	int i;

	if (sscanf(s, "%x:%x:%x:%x:%x:%x", &b[0], &b[1], &b[2], &b[3],
	    &b[4], &b[5]) != 6 &&
	    sscanf(s, "%x-%x-%x-%x-%x-%x", &b[0], &b[1], &b[2], &b[3],
	    &b[4], &b[5]) != 6)
		return -1;
	for (i = 0; i < 6; i++) {
		if (b[i] > 0xff)
			return -1;
		mac[i] = (uint8_t)b[i];
	}
	return 0;
}

static int
parse_int(const char *s, int min, int max, int *out)
{
	char *end;
	long v;

	errno = 0;
	v = strtol(s, &end, 10);
	if (errno || end == s || *trim(end) != '\0' || v < min || v > max)
		return -1;
	*out = (int)v;
	return 0;
}

static const char *
mac_str(const uint8_t mac[6])
{
	static char buf[18];

	snprintf(buf, sizeof(buf), "%02x:%02x:%02x:%02x:%02x:%02x",
	    mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
	return buf;
}

/* ---------- Wake-on-LAN ---------- */

static int
send_wol(const uint8_t mac[6], struct in_addr bcast, uint16_t port)
{
	uint8_t pkt[102];
	struct sockaddr_in sin;
	int s, on = 1, i;
	ssize_t n;

	memset(pkt, 0xff, 6);
	for (i = 0; i < 16; i++)
		memcpy(pkt + 6 + i * 6, mac, 6);

	if ((s = socket(AF_INET, SOCK_DGRAM, 0)) < 0) {
		logmsg(LOG_ERR, "socket(UDP): %s", strerror(errno));
		return -1;
	}
	if (setsockopt(s, SOL_SOCKET, SO_BROADCAST, &on, sizeof(on)) < 0) {
		logmsg(LOG_ERR, "setsockopt(SO_BROADCAST): %s", strerror(errno));
		close(s);
		return -1;
	}
	memset(&sin, 0, sizeof(sin));
	sin.sin_family = AF_INET;
	sin.sin_port = htons(port);
	sin.sin_addr = bcast;
	n = sendto(s, pkt, sizeof(pkt), 0, (struct sockaddr *)&sin,
	    sizeof(sin));
	close(s);
	if (n != (ssize_t)sizeof(pkt)) {
		logmsg(LOG_ERR, "sendto %s:%u: %s", inet_ntoa(bcast), port,
		    strerror(errno));
		return -1;
	}
	return 0;
}

static void
host_wol(struct host *h, const char *reason)
{
	if (send_wol(h->mac, h->bcast, h->port) == 0) {
		h->last_wol = time(NULL);
		h->wol_count++;
		logmsg(LOG_NOTICE, "WOL sent to %s (%s) via %s:%u [%s]",
		    h->name, mac_str(h->mac), inet_ntoa(h->bcast), h->port,
		    reason);
	}
}

/* ---------- ICMP ---------- */

static uint16_t
in_cksum(const void *data, size_t len)
{
	const uint16_t *w = data;
	uint32_t sum = 0;

	while (len > 1) {
		sum += *w++;
		len -= 2;
	}
	if (len == 1)
		sum += *(const uint8_t *)w;
	sum = (sum >> 16) + (sum & 0xffff);
	sum += (sum >> 16);
	return (uint16_t)~sum;
}

static void
send_ping(struct host *h)
{
	uint8_t buf[sizeof(struct icmp) + 8];
	struct icmp *icp = (struct icmp *)buf;
	struct sockaddr_in sin;

	memset(buf, 0, sizeof(buf));
	icp->icmp_type = ICMP_ECHO;
	icp->icmp_code = 0;
	icp->icmp_id = htons(ping_ident);
	h->ping_seq = ++ping_counter;
	icp->icmp_seq = htons(h->ping_seq);
	memcpy(buf + 8, "wolsched", 8);
	icp->icmp_cksum = in_cksum(buf, sizeof(buf));

	memset(&sin, 0, sizeof(sin));
	sin.sin_family = AF_INET;
	sin.sin_addr = h->ip;

	h->ping_sent = time(NULL);
	h->ping_pending = 1;
	if (sendto(icmp_sock, buf, sizeof(buf), 0, (struct sockaddr *)&sin,
	    sizeof(sin)) < 0)
		logmsg(LOG_DEBUG, "ping %s (%s): %s", h->name,
		    inet_ntoa(h->ip), strerror(errno));
}

static void
host_up(struct host *h)
{
	if (h->state != ST_UP)
		logmsg(LOG_NOTICE, "host %s (%s) is UP", h->name,
		    inet_ntoa(h->ip));
	h->state = ST_UP;
	h->fails = 0;
	h->ping_pending = 0;
	h->last_reply = time(NULL);
}

static void
recv_pings(void)
{
	uint8_t buf[1500];
	struct sockaddr_in from;
	socklen_t fromlen;
	struct ip *ip;
	struct icmp *icp;
	ssize_t n;
	int hlen, i;

	for (;;) {
		fromlen = sizeof(from);
		n = recvfrom(icmp_sock, buf, sizeof(buf), 0,
		    (struct sockaddr *)&from, &fromlen);
		if (n < 0)
			return; /* EAGAIN or error: nothing more to read */
		ip = (struct ip *)buf;
		hlen = ip->ip_hl << 2;
		if (n < hlen + ICMP_MINLEN)
			continue;
		icp = (struct icmp *)(buf + hlen);
		if (icp->icmp_type != ICMP_ECHOREPLY ||
		    ntohs(icp->icmp_id) != ping_ident)
			continue;
		for (i = 0; i < nhosts; i++) {
			if (hosts[i].keepalive &&
			    hosts[i].ip.s_addr == from.sin_addr.s_addr)
				host_up(&hosts[i]);
		}
	}
}

static int
open_icmp(void)
{
	int fl;

	if (icmp_sock >= 0)
		return 0;
	if ((icmp_sock = socket(AF_INET, SOCK_RAW, IPPROTO_ICMP)) < 0) {
		logmsg(LOG_ERR, "socket(ICMP): %s (are you root?)",
		    strerror(errno));
		return -1;
	}
	fl = fcntl(icmp_sock, F_GETFL);
	fcntl(icmp_sock, F_SETFL, fl | O_NONBLOCK);
	return 0;
}

/* ---------- config ---------- */

static void
host_defaults(struct host *h)
{
	memset(h, 0, sizeof(*h));
	snprintf(h->name, sizeof(h->name), "host");
	h->bcast.s_addr = htonl(INADDR_BROADCAST);
	h->port = 9;
	h->ping_interval = 10;
	h->ping_timeout = 2;
	h->fail_threshold = 3;
	h->wol_retry = 30;
}

static int
host_valid(const struct host *h, const char *path, int line, int has_mac)
{
	if (!has_mac) {
		logmsg(LOG_ERR, "%s:%d: host '%s' has no valid mac", path,
		    line, h->name);
		return 0;
	}
	if (h->keepalive && h->ip.s_addr == 0) {
		logmsg(LOG_ERR, "%s:%d: host '%s' has keepalive but no ip",
		    path, line, h->name);
		return 0;
	}
	return 1;
}

static int
load_config(const char *path, struct host *out, int *nout)
{
	FILE *f;
	char buf[512], *line, *key, *val, *eq;
	struct host cur;
	int lineno = 0, in_host = 0, has_mac = 0, n = 0, err = 0, v;

	if ((f = fopen(path, "r")) == NULL) {
		logmsg(LOG_ERR, "cannot open %s: %s", path, strerror(errno));
		return -1;
	}

#define FLUSH_HOST() do {						\
	if (in_host && host_valid(&cur, path, lineno, has_mac)) {	\
		if (n < MAX_HOSTS)					\
			out[n++] = cur;					\
		else							\
			logmsg(LOG_WARNING, "too many hosts, ignoring '%s'", \
			    cur.name);					\
	}								\
} while (0)

	while (fgets(buf, sizeof(buf), f) != NULL) {
		lineno++;
		line = trim(buf);
		if (*line == '\0' || *line == '#' || *line == ';')
			continue;
		if (strcmp(line, "[host]") == 0) {
			FLUSH_HOST();
			host_defaults(&cur);
			in_host = 1;
			has_mac = 0;
			continue;
		}
		if (!in_host || (eq = strchr(line, '=')) == NULL) {
			logmsg(LOG_WARNING, "%s:%d: ignoring '%s'", path,
			    lineno, line);
			continue;
		}
		*eq = '\0';
		key = trim(line);
		val = trim(eq + 1);

		if (strcmp(key, "name") == 0) {
			snprintf(cur.name, sizeof(cur.name), "%s", val);
		} else if (strcmp(key, "mac") == 0) {
			if (parse_mac(val, cur.mac) == 0)
				has_mac = 1;
			else
				err = 1;
		} else if (strcmp(key, "broadcast") == 0) {
			if (inet_pton(AF_INET, val, &cur.bcast) != 1)
				err = 1;
		} else if (strcmp(key, "ip") == 0) {
			if (*val != '\0' && inet_pton(AF_INET, val, &cur.ip) != 1)
				err = 1;
		} else if (strcmp(key, "port") == 0) {
			if (parse_int(val, 1, 65535, &v) == 0)
				cur.port = (uint16_t)v;
			else
				err = 1;
		} else if (strcmp(key, "interval") == 0) {
			err |= parse_int(val, 0, 86400 * 365, &cur.interval) != 0;
		} else if (strcmp(key, "keepalive") == 0) {
			err |= parse_int(val, 0, 1, &cur.keepalive) != 0;
		} else if (strcmp(key, "ping_interval") == 0) {
			err |= parse_int(val, 1, 3600, &cur.ping_interval) != 0;
		} else if (strcmp(key, "ping_timeout") == 0) {
			err |= parse_int(val, 1, 60, &cur.ping_timeout) != 0;
		} else if (strcmp(key, "fail_threshold") == 0) {
			err |= parse_int(val, 1, 100, &cur.fail_threshold) != 0;
		} else if (strcmp(key, "wol_retry") == 0) {
			err |= parse_int(val, 1, 86400, &cur.wol_retry) != 0;
		} else {
			logmsg(LOG_WARNING, "%s:%d: unknown key '%s'", path,
			    lineno, key);
			continue;
		}
		if (err) {
			logmsg(LOG_ERR, "%s:%d: invalid value for '%s': '%s'",
			    path, lineno, key, val);
			err = 0;
			if (strcmp(key, "mac") == 0)
				has_mac = 0;
		}
	}
	FLUSH_HOST();
#undef FLUSH_HOST
	fclose(f);
	*nout = n;
	return 0;
}

static void
apply_config(void)
{
	static struct host fresh[MAX_HOSTS];
	int n, i, j;
	time_t now = time(NULL);

	if (load_config(conf_path, fresh, &n) < 0)
		return;

	/* keep runtime state for hosts that did not change identity */
	for (i = 0; i < n; i++) {
		struct host *h = &fresh[i];

		for (j = 0; j < nhosts; j++) {
			if (memcmp(hosts[j].mac, h->mac, 6) == 0 &&
			    hosts[j].ip.s_addr == h->ip.s_addr) {
				h->state = hosts[j].state;
				h->fails = hosts[j].fails;
				h->last_reply = hosts[j].last_reply;
				h->last_wol = hosts[j].last_wol;
				h->wol_count = hosts[j].wol_count;
				if (hosts[j].interval == h->interval)
					h->next_wol = hosts[j].next_wol;
				break;
			}
		}
		if (h->interval > 0 && h->next_wol == 0)
			h->next_wol = now + h->interval;
		h->next_ping = now;
		h->next_retry_wol = now;
		h->ping_pending = 0;
	}
	memcpy(hosts, fresh, sizeof(struct host) * n);
	nhosts = n;

	for (i = 0; i < nhosts; i++)
		if (hosts[i].keepalive) {
			open_icmp();
			break;
		}

	logmsg(LOG_NOTICE, "loaded %d host(s) from %s", nhosts, conf_path);
	for (i = 0; i < nhosts; i++) {
		struct host *h = &hosts[i];

		logmsg(LOG_INFO, "  %s mac=%s bcast=%s:%u interval=%ds "
		    "keepalive=%s", h->name, mac_str(h->mac),
		    inet_ntoa(h->bcast), h->port, h->interval,
		    h->keepalive ? "on" : "off");
	}
}

/* ---------- status file ---------- */

static const char *
state_str(const struct host *h)
{
	if (!h->keepalive)
		return "n/a";
	switch (h->state) {
	case ST_UP:   return "up";
	case ST_DOWN: return "down";
	default:      return "unknown";
	}
}

static void
write_status(void)
{
	char tmp[256];
	FILE *f;
	int i;

	snprintf(tmp, sizeof(tmp), "%s.tmp", status_path);
	if ((f = fopen(tmp, "w")) == NULL)
		return;
	fprintf(f, "# name\tmac\tip\tstate\tlast_reply\tlast_wol\twol_count"
	    "\tnext_wol\n");
	for (i = 0; i < nhosts; i++) {
		struct host *h = &hosts[i];

		fprintf(f, "%s\t%s\t%s\t%s\t%ld\t%ld\t%lu\t%ld\n", h->name,
		    mac_str(h->mac),
		    h->keepalive ? inet_ntoa(h->ip) : "-", state_str(h),
		    (long)h->last_reply, (long)h->last_wol, h->wol_count,
		    (long)h->next_wol);
	}
	fclose(f);
	rename(tmp, status_path);
}

/* ---------- main loop ---------- */

static void
tick(void)
{
	time_t now = time(NULL);
	int i;

	for (i = 0; i < nhosts; i++) {
		struct host *h = &hosts[i];

		/* scheduled WOL */
		if (h->interval > 0 && now >= h->next_wol) {
			host_wol(h, "schedule");
			h->next_wol = now + h->interval;
		}

		if (!h->keepalive || icmp_sock < 0)
			continue;

		/* ping timeout */
		if (h->ping_pending && now - h->ping_sent >= h->ping_timeout) {
			h->ping_pending = 0;
			h->fails++;
			logmsg(LOG_DEBUG, "ping timeout %s (%d/%d)", h->name,
			    h->fails, h->fail_threshold);
			if (h->fails >= h->fail_threshold &&
			    h->state != ST_DOWN) {
				logmsg(LOG_WARNING, "host %s (%s) is DOWN, "
				    "sending WOL every %ds", h->name,
				    inet_ntoa(h->ip), h->wol_retry);
				h->state = ST_DOWN;
				h->next_retry_wol = now;
			}
		}

		/* keep-alive WOL while down */
		if (h->state == ST_DOWN && now >= h->next_retry_wol) {
			host_wol(h, "keep-alive");
			h->next_retry_wol = now + h->wol_retry;
		}

		if (!h->ping_pending && now >= h->next_ping) {
			send_ping(h);
			h->next_ping = now + h->ping_interval;
		}
	}
}

static void
on_signal(int sig)
{
	if (sig == SIGHUP)
		got_hup = 1;
	else
		got_term = 1;
}

static void
write_pidfile(void)
{
	FILE *f;

	if ((f = fopen(pid_path, "w")) == NULL) {
		logmsg(LOG_WARNING, "cannot write %s: %s", pid_path,
		    strerror(errno));
		return;
	}
	fprintf(f, "%ld\n", (long)getpid());
	fclose(f);
}

static void
usage(void)
{
	fprintf(stderr,
	    "wolscheduler %s\n"
	    "usage: wolscheduler [-fd] [-c conf] [-p pidfile] [-s statusfile]\n"
	    "       wolscheduler -t [-c conf]          test config and exit\n"
	    "       wolscheduler -w mac [-b broadcast] [-P port]   send one WOL\n",
	    VERSION);
	exit(1);
}

int
main(int argc, char *argv[])
{
	struct sigaction sa;
	struct timeval tv;
	fd_set rfds;
	const char *wol_mac = NULL, *wol_bcast = "255.255.255.255";
	int ch, test = 0, wol_port = 9, n;
	time_t last_status = 0;

	while ((ch = getopt(argc, argv, "b:c:dfhp:P:s:tVw:")) != -1) {
		switch (ch) {
		case 'b': wol_bcast = optarg; break;
		case 'c': conf_path = optarg; break;
		case 'd': debug = 1; break;
		case 'f': foreground = 1; break;
		case 'p': pid_path = optarg; break;
		case 'P':
			if (parse_int(optarg, 1, 65535, &wol_port) < 0)
				usage();
			break;
		case 's': status_path = optarg; break;
		case 't': test = 1; break;
		case 'V': printf("wolscheduler %s\n", VERSION); return 0;
		case 'w': wol_mac = optarg; break;
		default: usage();
		}
	}

	/* one-shot WOL */
	if (wol_mac != NULL) {
		uint8_t mac[6];
		struct in_addr b;

		foreground = 1;
		if (parse_mac(wol_mac, mac) < 0 ||
		    inet_pton(AF_INET, wol_bcast, &b) != 1) {
			fprintf(stderr, "invalid mac or broadcast address\n");
			return 1;
		}
		if (send_wol(mac, b, (uint16_t)wol_port) < 0)
			return 1;
		printf("WOL sent to %s via %s:%d\n", mac_str(mac), wol_bcast,
		    wol_port);
		return 0;
	}

	if (test) {
		foreground = 1;
		debug = 1;
		if (load_config(conf_path, hosts, &n) < 0)
			return 1;
		printf("%s: %d valid host(s)\n", conf_path, n);
		return 0;
	}

	openlog("wolscheduler", LOG_PID, LOG_DAEMON);
	if (!foreground && daemon(0, 0) < 0) {
		logmsg(LOG_ERR, "daemon: %s", strerror(errno));
		return 1;
	}
	write_pidfile();

	memset(&sa, 0, sizeof(sa));
	sa.sa_handler = on_signal;
	sigemptyset(&sa.sa_mask);
	sigaction(SIGHUP, &sa, NULL);
	sigaction(SIGTERM, &sa, NULL);
	sigaction(SIGINT, &sa, NULL);
	signal(SIGPIPE, SIG_IGN);

	ping_ident = (uint16_t)(getpid() & 0xffff);
	logmsg(LOG_NOTICE, "starting wolscheduler %s", VERSION);
	apply_config();

	while (!got_term) {
		if (got_hup) {
			got_hup = 0;
			logmsg(LOG_NOTICE, "SIGHUP received, reloading config");
			apply_config();
		}

		tick();

		if (time(NULL) != last_status) {
			write_status();
			last_status = time(NULL);
		}

		FD_ZERO(&rfds);
		if (icmp_sock >= 0)
			FD_SET(icmp_sock, &rfds);
		tv.tv_sec = 1;
		tv.tv_usec = 0;
		n = select(icmp_sock >= 0 ? icmp_sock + 1 : 0, &rfds, NULL,
		    NULL, &tv);
		if (n > 0 && FD_ISSET(icmp_sock, &rfds))
			recv_pings();
	}

	logmsg(LOG_NOTICE, "exiting");
	unlink(pid_path);
	unlink(status_path);
	if (icmp_sock >= 0)
		close(icmp_sock);
	return 0;
}
